# coding: utf-8

# flake8: noqa

"""
    EZ Diffusion API

    Simple API for creating AI-driven generative image and video.  This API provides image generation capabilities using diffusion models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ImageGenerationApi",
    "SystemApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CNProcessorType",
    "ControlNetParams",
    "ErrorResponse",
    "ImageGenerateRequest",
    "ImageGenerationHistoryResponse",
    "ImageGenerationParams",
    "ImageGenerationParamsDimensions",
    "ImageGenerationParamsPipelineOptimizations",
    "ImageGenerationResponse",
    "ImageInput",
    "ImageToImageParams",
    "InpaintParams",
    "LoraParams",
    "MemoryInfoResponse",
    "OpResult",
    "OpStatus",
    "ValidationError",
    "ValidationErrorDetailInner",
    "ValidationErrorDetailInnerLocInner",
]

# import apis into sdk package
from ez_diffusion_client.api.image_generation_api import ImageGenerationApi as ImageGenerationApi
from ez_diffusion_client.api.system_api import SystemApi as SystemApi

# import ApiClient
from ez_diffusion_client.api_response import ApiResponse as ApiResponse
from ez_diffusion_client.api_client import ApiClient as ApiClient
from ez_diffusion_client.configuration import Configuration as Configuration
from ez_diffusion_client.exceptions import OpenApiException as OpenApiException
from ez_diffusion_client.exceptions import ApiTypeError as ApiTypeError
from ez_diffusion_client.exceptions import ApiValueError as ApiValueError
from ez_diffusion_client.exceptions import ApiKeyError as ApiKeyError
from ez_diffusion_client.exceptions import ApiAttributeError as ApiAttributeError
from ez_diffusion_client.exceptions import ApiException as ApiException

# import models into sdk package
from ez_diffusion_client.models.cn_processor_type import CNProcessorType as CNProcessorType
from ez_diffusion_client.models.control_net_params import ControlNetParams as ControlNetParams
from ez_diffusion_client.models.error_response import ErrorResponse as ErrorResponse
from ez_diffusion_client.models.image_generate_request import ImageGenerateRequest as ImageGenerateRequest
from ez_diffusion_client.models.image_generation_history_response import ImageGenerationHistoryResponse as ImageGenerationHistoryResponse
from ez_diffusion_client.models.image_generation_params import ImageGenerationParams as ImageGenerationParams
from ez_diffusion_client.models.image_generation_params_dimensions import ImageGenerationParamsDimensions as ImageGenerationParamsDimensions
from ez_diffusion_client.models.image_generation_params_pipeline_optimizations import ImageGenerationParamsPipelineOptimizations as ImageGenerationParamsPipelineOptimizations
from ez_diffusion_client.models.image_generation_response import ImageGenerationResponse as ImageGenerationResponse
from ez_diffusion_client.models.image_input import ImageInput as ImageInput
from ez_diffusion_client.models.image_to_image_params import ImageToImageParams as ImageToImageParams
from ez_diffusion_client.models.inpaint_params import InpaintParams as InpaintParams
from ez_diffusion_client.models.lora_params import LoraParams as LoraParams
from ez_diffusion_client.models.memory_info_response import MemoryInfoResponse as MemoryInfoResponse
from ez_diffusion_client.models.op_result import OpResult as OpResult
from ez_diffusion_client.models.op_status import OpStatus as OpStatus
from ez_diffusion_client.models.validation_error import ValidationError as ValidationError
from ez_diffusion_client.models.validation_error_detail_inner import ValidationErrorDetailInner as ValidationErrorDetailInner
from ez_diffusion_client.models.validation_error_detail_inner_loc_inner import ValidationErrorDetailInnerLocInner as ValidationErrorDetailInnerLocInner
