# coding: utf-8

"""
    EZ Diffusion API

    Simple API for creating AI-driven generative image and video.  This API provides image generation capabilities using diffusion models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ez_diffusion_client.api.image_generation_api import ImageGenerationApi


class TestImageGenerationApi(unittest.TestCase):
    """ImageGenerationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageGenerationApi()

    def tearDown(self) -> None:
        pass

    def test_generate_image(self) -> None:
        """Test case for generate_image

        Generate image synchronously
        """
        pass

    def test_get_image_gen_history(self) -> None:
        """Test case for get_image_gen_history

        Get image generation history
        """
        pass

    def test_image_to_image(self) -> None:
        """Test case for image_to_image

        Alias of /image-gen with additional validation specific to image-to-image requests
        """
        pass

    def test_inpaint(self) -> None:
        """Test case for inpaint

        Alias of /image-gen with additional validation specific to inpaint requests
        """
        pass

    def test_text_to_image(self) -> None:
        """Test case for text_to_image

        Alias of /image-gen with additional validation specific to text-to-image requests
        """
        pass


if __name__ == '__main__':
    unittest.main()
