# coding: utf-8

"""
    EZ Diffusion API

    Simple API for creating AI-driven generative image and video.  This API provides image generation capabilities using diffusion models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ez_diffusion_client.models.op_status import OpStatus

class TestOpStatus(unittest.TestCase):
    """OpStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpStatus(self):
        """Test OpStatus"""
        # inst = OpStatus()

if __name__ == '__main__':
    unittest.main()
