/* tslint:disable */
/* eslint-disable */
/**
 * SDXL Worker API
 * SDXL Image Generation API for RunPod serverless workers.  This API provides image generation capabilities using Stable Diffusion XL (SDXL) models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet Union with 8 control modes - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageToImageParams
 */
export interface ImageToImageParams {
    /**
     * Base64 encoded starting image for image-to-image generation
     * @type {string}
     * @memberof ImageToImageParams
     */
    startingImage: string;
}

/**
 * Check if a given object implements the ImageToImageParams interface.
 */
export function instanceOfImageToImageParams(value: object): value is ImageToImageParams {
    if (!('startingImage' in value) || value['startingImage'] === undefined) return false;
    return true;
}

export function ImageToImageParamsFromJSON(json: any): ImageToImageParams {
    return ImageToImageParamsFromJSONTyped(json, false);
}

export function ImageToImageParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageToImageParams {
    if (json == null) {
        return json;
    }
    return {
        
        'startingImage': json['starting_image'],
    };
}

export function ImageToImageParamsToJSON(json: any): ImageToImageParams {
    return ImageToImageParamsToJSONTyped(json, false);
}

export function ImageToImageParamsToJSONTyped(value?: ImageToImageParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'starting_image': value['startingImage'],
    };
}

