/* tslint:disable */
/* eslint-disable */
/**
 * SDXL Worker API
 * SDXL Image Generation API for RunPod serverless workers.  This API provides image generation capabilities using Stable Diffusion XL (SDXL) models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet Union with 8 control modes - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type LoraParamsScale
 * LoRA scaling factor (can be single value or per-layer dict)
 * @export
 */
export type LoraParamsScale = number | { [key: string]: number; };

export function LoraParamsScaleFromJSON(json: any): LoraParamsScale {
    return LoraParamsScaleFromJSONTyped(json, false);
}

export function LoraParamsScaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoraParamsScale {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function LoraParamsScaleToJSON(json: any): any {
    return LoraParamsScaleToJSONTyped(json, false);
}

export function LoraParamsScaleToJSONTyped(value?: LoraParamsScale | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

