/* tslint:disable */
/* eslint-disable */
/**
 * SDXL Worker API
 * SDXL Image Generation API for RunPod serverless workers.  This API provides image generation capabilities using Stable Diffusion XL (SDXL) models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet Union with 8 control modes - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemoryInfoResponse
 */
export interface MemoryInfoResponse {
    /**
     * Memory usage information
     * @type {{ [key: string]: string; }}
     * @memberof MemoryInfoResponse
     */
    info: { [key: string]: string; };
}

/**
 * Check if a given object implements the MemoryInfoResponse interface.
 */
export function instanceOfMemoryInfoResponse(value: object): value is MemoryInfoResponse {
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function MemoryInfoResponseFromJSON(json: any): MemoryInfoResponse {
    return MemoryInfoResponseFromJSONTyped(json, false);
}

export function MemoryInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'],
    };
}

export function MemoryInfoResponseToJSON(json: any): MemoryInfoResponse {
    return MemoryInfoResponseToJSONTyped(json, false);
}

export function MemoryInfoResponseToJSONTyped(value?: MemoryInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': value['info'],
    };
}

