/* tslint:disable */
/* eslint-disable */
/**
 * SDXL Worker API
 * SDXL Image Generation API for RunPod serverless workers.  This API provides image generation capabilities using Stable Diffusion XL (SDXL) models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet Union with 8 control modes - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Operation status
 * @export
 */
export const OpStatus = {
    Pending: 'PENDING',
    Success: 'SUCCESS',
    Failure: 'FAILURE'
} as const;
export type OpStatus = typeof OpStatus[keyof typeof OpStatus];


export function instanceOfOpStatus(value: any): boolean {
    for (const key in OpStatus) {
        if (Object.prototype.hasOwnProperty.call(OpStatus, key)) {
            if (OpStatus[key as keyof typeof OpStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OpStatusFromJSON(json: any): OpStatus {
    return OpStatusFromJSONTyped(json, false);
}

export function OpStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpStatus {
    return json as OpStatus;
}

export function OpStatusToJSON(value?: OpStatus | null): any {
    return value as any;
}

export function OpStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OpStatus {
    return value as OpStatus;
}

