/* tslint:disable */
/* eslint-disable */
/**
 * SDXL Worker API
 * SDXL Image Generation API for RunPod serverless workers.  This API provides image generation capabilities using Stable Diffusion XL (SDXL) models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet Union with 8 control modes - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorDetailInnerLocInner } from './ValidationErrorDetailInnerLocInner';
import {
    ValidationErrorDetailInnerLocInnerFromJSON,
    ValidationErrorDetailInnerLocInnerFromJSONTyped,
    ValidationErrorDetailInnerLocInnerToJSON,
    ValidationErrorDetailInnerLocInnerToJSONTyped,
} from './ValidationErrorDetailInnerLocInner';

/**
 * 
 * @export
 * @interface ValidationErrorDetailInner
 */
export interface ValidationErrorDetailInner {
    /**
     * 
     * @type {Array<ValidationErrorDetailInnerLocInner>}
     * @memberof ValidationErrorDetailInner
     */
    loc?: Array<ValidationErrorDetailInnerLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetailInner
     */
    msg?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetailInner
     */
    type?: string;
}

/**
 * Check if a given object implements the ValidationErrorDetailInner interface.
 */
export function instanceOfValidationErrorDetailInner(value: object): value is ValidationErrorDetailInner {
    return true;
}

export function ValidationErrorDetailInnerFromJSON(json: any): ValidationErrorDetailInner {
    return ValidationErrorDetailInnerFromJSONTyped(json, false);
}

export function ValidationErrorDetailInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetailInner {
    if (json == null) {
        return json;
    }
    return {
        
        'loc': json['loc'] == null ? undefined : ((json['loc'] as Array<any>).map(ValidationErrorDetailInnerLocInnerFromJSON)),
        'msg': json['msg'] == null ? undefined : json['msg'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ValidationErrorDetailInnerToJSON(json: any): ValidationErrorDetailInner {
    return ValidationErrorDetailInnerToJSONTyped(json, false);
}

export function ValidationErrorDetailInnerToJSONTyped(value?: ValidationErrorDetailInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'loc': value['loc'] == null ? undefined : ((value['loc'] as Array<any>).map(ValidationErrorDetailInnerLocInnerToJSON)),
        'msg': value['msg'],
        'type': value['type'],
    };
}

