/* tslint:disable */
/* eslint-disable */
/**
 * SDXL Worker API
 * SDXL Image Generation API for RunPod serverless workers.  This API provides image generation capabilities using Stable Diffusion XL (SDXL) models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet Union with 8 control modes - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ValidationErrorDetailInnerLocInner
 * 
 * @export
 */
export type ValidationErrorDetailInnerLocInner = number | string;

export function ValidationErrorDetailInnerLocInnerFromJSON(json: any): ValidationErrorDetailInnerLocInner {
    return ValidationErrorDetailInnerLocInnerFromJSONTyped(json, false);
}

export function ValidationErrorDetailInnerLocInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetailInnerLocInner {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function ValidationErrorDetailInnerLocInnerToJSON(json: any): any {
    return ValidationErrorDetailInnerLocInnerToJSONTyped(json, false);
}

export function ValidationErrorDetailInnerLocInnerToJSONTyped(value?: ValidationErrorDetailInnerLocInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

