# coding: utf-8

# flake8: noqa
"""
    EZ Diffusion API

    Simple API for creating AI-driven generative image and video.  This API provides image generation capabilities using diffusion models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ez_diffusion_client.models.cn_processor_type import CNProcessorType
from ez_diffusion_client.models.control_net_params import ControlNetParams
from ez_diffusion_client.models.error_response import ErrorResponse
from ez_diffusion_client.models.image_generate_request import ImageGenerateRequest
from ez_diffusion_client.models.image_generation_history_response import ImageGenerationHistoryResponse
from ez_diffusion_client.models.image_generation_params import ImageGenerationParams
from ez_diffusion_client.models.image_generation_params_dimensions import ImageGenerationParamsDimensions
from ez_diffusion_client.models.image_generation_params_pipeline_optimizations import ImageGenerationParamsPipelineOptimizations
from ez_diffusion_client.models.image_generation_response import ImageGenerationResponse
from ez_diffusion_client.models.image_input import ImageInput
from ez_diffusion_client.models.image_to_image_params import ImageToImageParams
from ez_diffusion_client.models.inpaint_params import InpaintParams
from ez_diffusion_client.models.lora_params import LoraParams
from ez_diffusion_client.models.memory_info_response import MemoryInfoResponse
from ez_diffusion_client.models.op_result import OpResult
from ez_diffusion_client.models.op_status import OpStatus
from ez_diffusion_client.models.validation_error import ValidationError
from ez_diffusion_client.models.validation_error_detail_inner import ValidationErrorDetailInner
from ez_diffusion_client.models.validation_error_detail_inner_loc_inner import ValidationErrorDetailInnerLocInner
