# coding: utf-8

"""
    EZ Diffusion API

    Simple API for creating AI-driven generative image and video.  This API provides image generation capabilities using diffusion models with support for: - Text-to-Image generation - Image-to-Image generation   - Inpainting - ControlNet - LoRA adapters for fine-tuned models - Multiple schedulers and configurations  The service runs on GPU-enabled infrastructure and returns high-quality generated images based on text prompts and optional control inputs. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CNProcessorType(str, Enum):
    """
    ControlNet preprocessing method
    """

    """
    allowed enum values
    """
    CANNY = 'canny'
    DEPTH_LERES = 'depth_leres'
    DEPTH_LERES_PLUS_PLUS = 'depth_leres++'
    DEPTH_MIDAS = 'depth_midas'
    DEPTH_ZOE = 'depth_zoe'
    LINEART_ANIME = 'lineart_anime'
    LINEART_COARSE = 'lineart_coarse'
    LINEART_REALISTIC = 'lineart_realistic'
    MEDIAPIPE_FACE = 'mediapipe_face'
    MLSD = 'mlsd'
    NORMAL_BAE = 'normal_bae'
    OPENPOSE = 'openpose'
    OPENPOSE_FACE = 'openpose_face'
    OPENPOSE_FACEONLY = 'openpose_faceonly'
    OPENPOSE_FULL = 'openpose_full'
    OPENPOSE_HAND = 'openpose_hand'
    SCRIBBLE_HED = 'scribble_hed'
    SCRIBBLE_PIDINET = 'scribble_pidinet'
    SHUFFLE = 'shuffle'
    SOFTEDGE_HED = 'softedge_hed'
    SOFTEDGE_HEDSAFE = 'softedge_hedsafe'
    SOFTEDGE_PIDINET = 'softedge_pidinet'
    SOFTEDGE_PIDSAFE = 'softedge_pidsafe'
    DWPOSE = 'dwpose'
    OPENPOSE_HAND_BODY = 'openpose_hand_body'
    SEGMENTATION = 'segmentation'
    INPAINT = 'inpaint'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CNProcessorType from a JSON string"""
        return cls(json.loads(json_str))


