[project]
name = "sdxl-workers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "diffusers[torch]>=0.34.0",
    "runpod>=1.7.13",
    "transformers>=4.54.0",
]
